name: 🐞 OpenCart Extension Bug Report
description: Create a report to help us improve this OpenCart extension
title: "[BUG] "
labels: [bug]
assignees:
  - zsoltoroszlany82
body:
  - type: input
    attributes:
      label: Extension Version
      description: What version of the extension are you using?
      placeholder: e.g. 1.3.2
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the Bug
      description: Clearly describe what is going wrong.
      placeholder: e.g. Error appears when saving a new product in the admin panel.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Perform action '...'
        4. Observe error or unexpected behavior
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
      placeholder: The product should have saved without any error.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Error Logs or Messages
      description: Paste relevant logs, stack traces, or error messages here.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshots or Video
      description: If available, upload screenshots or a video showing the problem.
    validations:
      required: false

  - type: dropdown
    attributes:
      label: OpenCart Version
      description: Which version of OpenCart are you using?
      options:
        - 3.0.x
        - 4.0.x
        - Other (please specify below)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment Details
      description: Web server, PHP/MySQL version, theme, and other relevant details.
      placeholder: |
        - Web Server: Apache 2.4
        - PHP Version: 7.4
        - MySQL Version: 5.7
        - Theme: Journal3
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other relevant details that might help us reproduce or understand the issue.
    validations:
      required: false
